### ISSUE TITLE
Two icons are in the tray

### ISSUE THREAD

**Issue by ilinum** [kamhix/todoist-linux#10]
Ubuntu 15.10
![tray](https://cloud.githubusercontent.com/assets/5924452/18845379/310ff42c-83e7-11e6-96d8-ab4001cd43a5.png)

**Comment by kamhix** [comment]
is it the website version you've downloaded ?

**Comment by ilinum** [comment]
Yes

**Comment by kamhix** [comment]
ok. Maybe it's the nwjs version I used that is outdated. Can you try to download the last version and try it with the github version. Or wait until Sunday I will updated the version from  the website myself.

**Comment by TimmyzBeach** [comment]
I just downloaded the file today (Nov 11) from the website and I still see this issue. 

@kamhix - How would a newbie go about doing what you proposed above?

**Comment by kamhix** [comment]
@ilinum and @TimmyzBeach I've updated the application to the last version of nwjs and added a fix for the tray icon, it's on [Todoist Linux Website](http://todoistlinux.hakimouake.com). Can you try it and give some feedback

The issue was not related to the last version but to the tray script being called twice. I've added a fix now

Sorry for the inconvenience

**Comment by ilinum** [comment]
Yes, this fixes it!
Thank you!

**Comment by kamhix** [comment]
Glad to help !
Thanks you for the quick reply :)
