### ISSUE TITLE
Sign in with Google doesn't work. 

### ISSUE THREAD

**Issue by singularinstruction** [kamhix/todoist-linux#7]
Clicking on the link opens a new window, but it shows only white blankness. I waited for quite a bit, but nothing happens.

**Comment by kamhix** [comment]
I will check it during the week.
Sorry for the long time answer. I've been busy :disappointed_relieved:

**Comment by bkufo** [comment]
I have the same issue as @nanganinja I downloaded the code using git as instructed, but i would appreciate some tips on troubleshooting this issue. 
I am using Ubuntu 16.04 LTS and trying to login using 'log in with google account'.

**Comment by kamhix** [comment]
Hi @bkufo, did you try with the website version first ?

Also you can try to delete this directory and try again, 
"/home/username/.config/Todoist",

**Comment by bkufo** [comment]
I have the same issue as @nanganinja I downloaded the code using git as instructed, but i would appreciate some tips on troubleshooting this issue. 
I am using Ubuntu 16.04 LTS and trying to login using 'log in with google account'.

**Comment by bkufo** [comment]
@kamhix Hi there and thanks for such a fast response. Yes, i can use todoist on the web version on my machine in either chrome or Firefox and they work fine.
I deleted the folder that you mentioned but i still get the same error. i have attached a screenshot. The window on the right is the blank one that is mentioned. I am also using the 64-bit version of the application.
![screenshot from 2016-11-07 07-50-08](https://cloud.githubusercontent.com/assets/8074521/20048711/db7e9164-a4be-11e6-99a0-f0af0a20fe68.png)

**Comment by bkufo** [comment]
Hi again @kamhix, i created a new todoist account that doesn't use Google integration. this worked, but not smoothly. I got a message saying "You have been logged in. Click here if you are not auto redirected." After i clicked it, then i saw the todoist page on a new windows and then everything was fine.

I also downloaded nw separately, and ran it, so that i could debug what was going on with the google integration. I was able to run the program from the command line, from the downloaded source code. However, i got stuck with trying to do debugging. Any tips? I looked at the code that you made available and there was nothing special here about Google integration. I also saw that there were no crash logs stored in ~/.config/Todoist or ~/.config/nw

**Comment by kamhix** [comment]
@bkufo I pushed some changes on the repo, I update all the code to fit with the recent version of nwjs. You can pull and try again or simply go on the [Todoist linux website](http://todoistlinux.hakimouake.com) and download the beta,
If anything goes wrong, tell me, I will try to fix as soon as possible

Thanks

**Comment by bkufo** [comment]
@kamhix It worked perfectly! Thank you. : )
The packaging seems different when i unzipped the 64-bit package this time. For the v3, i could just click todoist in the file explorer. Now, i needed to run it from the command line, but that is also ok. : )
The icon is also a chromium one. 

...but i am a very happy user. Thanks for the fast turnaround. : )

**Comment by kamhix** [comment]
@bkufo 

> For the v3, i could just click todoist in the file explorer. Now, i needed to run it from the command line

I noticed it too. I tried to fix it but I couldn't, I was too tired  :sweat_smile:. Next time

Glad to here that :smile:
